In [1]:
# =============================================================================
# BASE IMPORTS, LOGGING SETUP
# =============================================================================
from trading.backtester.utils       import setup_logging
from trading.backtester.engine      import BacktestRunner, load_config, RunContext
from trading.backtester.performance import PerformanceReport

run = RunContext.create()
run_dir = run.run_dir
setup_logging(run_dir=run_dir)

backtest_config = load_config(file = 'default_backtest.yaml')

In [2]:
# =============================================================================
# STRATEGY CONSTRUCTION
# Replace ONLY this section when testing a different strategy
# =============================================================================

# 1. Import strategy + config
from trading.strategy_engine.strategies.directional import (
    MACrossover,
    MACrossoverConfig,
)

from trading.strategy_engine.features.trend import MAType


# 2. Define strategy parameters
strategy_config = MACrossoverConfig(
    fast_period=20,
    fast_type=MAType.EMA,
    slow_period=50,
    slow_type=MAType.SMA,
)


# 3. Build strategy object
strategy = MACrossover(strategy_config)

In [3]:
# =============================================================================
# RUN STRATEGY
# =============================================================================

run.save_configs(backtest_config, strategy_config)  

runner  = BacktestRunner(backtest_config, strategy)

try:
    results = runner.run()
    (run_dir / "SUCCESS").touch()

except Exception:
    (run_dir / "FAILED").touch()
    raise


results.save(run_dir)

2026-07-23 10:47:05 | INFO     | trading.backtester.engine.runner | Starting backtest run: MA_CROSS_ema_20_sma_50
2026-07-23 10:47:06 | INFO     | trading.backtester.engine.runner | Loaded 8760 bars from 2025-01-01 00:00:00+00:00 to 2025-12-31 23:00:00+00:00
2026-07-23 10:47:06 | INFO     | trading.backtester.engine.runner | Validated 8760 signals — no lookahead detected.
2026-07-23 10:47:06 | INFO     | trading.backtester.engine.runner | Phase 1 complete — 8760 bars, 215 signals.
2026-07-23 10:47:07 | INFO     | trading.backtester.engine.runner | Backtest complete: 8760 bars processed, final equity=30147.50
2026-07-23 10:47:07 | INFO     | trading.backtester.engine.results | Successfully saved backtest results to C:\Users\SBBus\trading\runs\20260723_00_399

In [4]:
# =============================================================================
# RESULTS
# =============================================================================


report = PerformanceReport(results.portfolio_history, results.trade_log)
report.save(run_dir)

report.display(backtest_config)

                             Value
Core
Symbol                     BTCUSDT
Interval                        1H
Start             2025-01-01 00:00
End               2026-01-01 00:00
Duration                  366 days
Bars                          8760
Starting Capital       $100,000.00
Final Capital           $30,147.50

                                      Value
Returns
Mean Bar Return           -0.01%  ($-12.60)
CAGR                 -69.85%  ($-69,852.50)
Net Return           -69.85%  ($-69,852.50)
Gross Return         -61.49%  ($-61,488.96)
Skew                                 -0.703
Kurtosis                             14.440
Hit Rate (Bar)                       47.99%
Median Bar Return          -0.01%  ($-5.66)
Avg Bar Win                0.30%  ($298.98)
Avg Bar Loss             -0.31%  ($-307.53)
Avg Bar Win/Loss                      0.972
Largest Bar Return       4.42%  ($4,418.46)
Smallest Bar Return    -5.27%  ($-5,271.97)

                                        Value
Risk
Max Drawdown           -72.00%  ($-72,004.11)
Max DD Duration                  8307.00 bars
Avg DD Duration                   784.91 bars
Avg Drawdown             -7.80%  ($-7,798.46)
Time in Drawdown                       98.56%
Sharpe (per bar)                       -0.027
Sharpe (annualised)                    -2.531
Long Sharpe                            -2.788
Short Sharpe                           -2.314
Sortino                                -3.442
Calmar                                 -0.970
VaR 95%                      0.68%  ($676.55)
VaR 99%                    1.39%  ($1,388.09)
CVaR 95%                   1.14%  ($1,143.47)
CVaR 99%                   2.07%  ($2,074.09)
Downside Deviation                     32.07%
Volatility                             43.68%
Longest Losing Streak                 15 bars

                                      Value
Costs
Total Fee Drag         23.55%  ($23,554.98)
Total Funding Drag       -0.91%  ($-912.76)
Total Costs            24.47%  ($24,467.74)
Fee % of Net                         21.34%
Funding % of Net                     -0.83%
Cost % of Net                        22.17%
Cost to Gross Ratio                   0.285
Fee Drag (Sharpe)                     0.539
Funding Drag (Sharpe)                 0.021
Avg Fee per Bar              0.00%  ($2.69)
Avg Fee per Trade                     0.001
Annualised Turnover                  454.3x
% Bars Paying Funding                 6.77%

                                   Value
Trade
Num Trades                           213
Avg Position Size                 97.70%
Max Position Size                116.66%
Avg Long Size                    100.40%
Avg Short Size                   -97.42%
Time Long                         50.47%
Time Short                        48.28%
Time Flat                          1.26%
Expectancy            -0.50%  ($-501.46)
Profit Factor                      0.597
Hit Rate (Trade)                  27.23%
Time in Market                    98.74%
Avg Holding Period          8650.00 bars
Largest Win           4.41%  ($4,411.09)
Largest Loss        -5.27%  ($-5,271.97)
Long PnL %                       -54.15%
Short PnL %                      -45.85%

In [5]:
# =============================================================================
# RESULTS
# =============================================================================

### Example of loading a run and displaying the results

from trading.backtester.performance.review import RunReview
run_dir = '20260722_04_d02'
run = RunReview.build(run_dir)

run.display()

                             Value
Core
Symbol                     BTCUSDT
Interval                        1H
Start             2025-01-01 00:00
End               2026-01-01 00:00
Duration                  366 days
Bars                          8760
Starting Capital       $100,000.00
Final Capital           $30,147.50

                                      Value
Returns
Mean Bar Return           -0.01%  ($-12.60)
CAGR                 -69.85%  ($-69,852.50)
Net Return           -69.85%  ($-69,852.50)
Gross Return         -61.49%  ($-61,488.96)
Skew                                 -0.703
Kurtosis                             14.440
Hit Rate (Bar)                       47.99%
Median Bar Return          -0.01%  ($-5.66)
Avg Bar Win                0.30%  ($298.98)
Avg Bar Loss             -0.31%  ($-307.53)
Avg Bar Win/Loss                      0.972
Largest Bar Return       4.42%  ($4,418.46)
Smallest Bar Return    -5.27%  ($-5,271.97)

                                        Value
Risk
Max Drawdown           -72.00%  ($-72,004.11)
Max DD Duration                  8307.00 bars
Avg DD Duration                   784.91 bars
Avg Drawdown             -7.80%  ($-7,798.46)
Time in Drawdown                       98.56%
Sharpe (per bar)                       -0.027
Sharpe (annualised)                    -2.531
Long Sharpe                            -2.788
Short Sharpe                           -2.314
Sortino                                -3.442
Calmar                                 -0.970
VaR 95%                      0.68%  ($676.55)
VaR 99%                    1.39%  ($1,388.09)
CVaR 95%                   1.14%  ($1,143.47)
CVaR 99%                   2.07%  ($2,074.09)
Downside Deviation                     32.07%
Volatility                             43.68%
Longest Losing Streak                 15 bars

                                      Value
Costs
Total Fee Drag         23.55%  ($23,554.98)
Total Funding Drag       -0.91%  ($-912.76)
Total Costs            24.47%  ($24,467.74)
Fee % of Net                         21.34%
Funding % of Net                     -0.83%
Cost % of Net                        22.17%
Cost to Gross Ratio                   0.285
Fee Drag (Sharpe)                     0.539
Funding Drag (Sharpe)                 0.021
Avg Fee per Bar              0.00%  ($2.69)
Avg Fee per Trade                     0.001
Annualised Turnover                  454.3x
% Bars Paying Funding                 6.77%

                                   Value
Trade
Num Trades                           213
Avg Position Size                 97.70%
Max Position Size                116.66%
Avg Long Size                    100.40%
Avg Short Size                   -97.42%
Time Long                         50.47%
Time Short                        48.28%
Time Flat                          1.26%
Expectancy            -0.50%  ($-501.46)
Profit Factor                      0.597
Hit Rate (Trade)                  27.23%
Time in Market                    98.74%
Avg Holding Period          8650.00 bars
Largest Win           4.41%  ($4,411.09)
Largest Loss        -5.27%  ($-5,271.97)
Long PnL %                       -54.15%
Short PnL %                      -45.85%